// plugins/8b8/make.js
//
// Turn the vendored parameter definition into the two things that have to
// agree with it: the profile's ports, and the scale table the module converts
// with.
//
// The 8b8 firmware stores its whole parameter bank as 42 bytes, each with its
// own range, and generate.py carries a display scale and offset alongside so
// that raw 0 to 48 reads as minus 24 to plus 24 semitones. A JigDAW port
// declares what a person and a host see, so the ports carry the displayed
// numbers and the module converts on the way in. That conversion is the pair
// that would drift: the table it uses is generated here from the same file
// the ports are, and tests/dsp/8b8.test.js binds both back to the firmware's
// own parameters.h.
//
// Run by ./build.sh. Writes profile.json and generated/param-map.h.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'

const here = import.meta.dirname
const read = name => JSON.parse(readFileSync(resolve(here, name), 'utf8'))

const head = read('plugin.json')
const { params, layoutVersion } = read('params.json')

// lv2's units vocabulary, keyed by what generate.py calls the unit. A unit
// this does not know is an error rather than a port with no unit, because a
// silently dropped unit is the difference between 4200 and 4200 Hz and
// nothing would report it. src/ui/Panel.js must know every name here, which
// tests/ui/Panel.test.js checks.
const UNITS = Object.freeze({
  '': null,
  Hz: 'hz',
  ms: 'ms',
  '%': 'pc',
  st: 'semitone12TET'
})

/**
 * The displayed value for a raw parameter byte.
 *
 * generate.py's own formula, and the inverse of what the module does in
 * jig_set_param. Rounded to six places because 0.1 times 3 is not 0.3 in
 * binary floating point, and a profile is a document people read.
 */
const display = (raw, p) => Number(((raw + p.offset) * p.scale).toFixed(6))

const ports = params.map(p => {
  if (!(p.unit in UNITS)) throw new Error(`${p.key} has unit ${JSON.stringify(p.unit)}, which has no lv2 units term here`)

  const port = {
    symbol: p.key,
    // Grouped, because 42 controls in a flat list are not navigable and the
    // generated panel prints lv2:name and nothing else.
    name: `${p.group}: ${p.label}`,
    default: display(p.default, p),
    minimum: display(p.min, p),
    maximum: display(p.max, p),
    paramIndex: p.index
  }

  const unit = UNITS[p.unit]
  if (unit) port.unit = unit
  if (p.kind === 'toggle') port.toggled = true
  if (p.kind === 'enum') {
    port.scalePoints = p.options.map((label, value) => ({ label, value }))
  }
  return port
})

const profile = { ...head, ports }
profile.note = 'GENERATED by plugins/8b8/make.js from plugin.json and params.json. Do not edit; run ./build.sh.'

writeFileSync(resolve(here, 'profile.json'), JSON.stringify(profile, null, 2) + '\n')

// The module's side of the same mapping. Fixed point is not worth it: the
// conversion happens on a parameter write, never in the render loop.
// Number.prototype.toFixed, not template interpolation: a scale of 1 prints
// as "1" and "1f" is not a C++ literal.
const rows = params.map(p =>
  `  { ${p.scale.toFixed(4)}f, ${p.offset} },   // ${p.index} ${p.key}`).join('\n')

const header = `// plugins/8b8/generated/param-map.h
//
// GENERATED by plugins/8b8/make.js from params.json. Do not edit.
//
// One row per parameter, in jig:paramIndex order: the display scale and the
// display offset that profile.json's ports were computed with. The module
// runs them backwards to recover the byte the firmware's setParam wants.
#pragma once

#define JIG_PARAM_COUNT ${params.length}

// The layout byte generate.py derives from the definition. The firmware
// compares it against what an EEPROM bank was saved under; it is here so a
// test can check that params.json and the vendored parameters.h are the same
// generation of the same file.
#define JIG_PARAM_LAYOUT_VERSION 0x${layoutVersion.toString(16).toUpperCase()}

struct JigParamScale { float scale; int offset; };

static const JigParamScale JIG_PARAM_SCALE[JIG_PARAM_COUNT] = {
${rows}
};
`

mkdirSync(resolve(here, 'generated'), { recursive: true })
writeFileSync(resolve(here, 'generated/param-map.h'), header)

console.log(`make.js: ${ports.length} ports into profile.json, ${params.length} rows into generated/param-map.h`)
