#!/usr/bin/env python3
"""Read the 8b8 parameter definition and print it as JSON.

generate.py in the 8bit8asterd repository is the single source of truth for
the controllable parameters: it generates the firmware's parameters.h and the
Web Serial panel from one list. This imports that list, runs its own
normalise() so the defaults it fills in are the same ones the firmware sees,
and prints it.

Importing rather than parsing, because a parser would be a second reading of
a format that has no specification, and it would agree with generate.py right
up until the day it did not.

Usage: read-params.py <path to the 8bit8asterd checkout>
"""
import contextlib
import importlib.util
import io
import json
import sys

if len(sys.argv) != 2:
    sys.exit(__doc__.strip().splitlines()[-1])

path = sys.argv[1] + "/generate.py"
spec = importlib.util.spec_from_file_location("b8_generate", path)
module = importlib.util.module_from_spec(spec)

# generate.py writes files when run as a script. It is guarded by
# __main__, but redirect anyway: an import that prints is an import that
# corrupts this script's only output channel.
with contextlib.redirect_stdout(io.StringIO()):
    spec.loader.exec_module(module)

module.normalise()

fields = ("index", "key", "label", "group", "kind", "min", "max", "default",
          "scale", "offset", "unit", "options")
params = [{f: p[f] for f in fields if f in p} for p in module.PARAMS]

print(json.dumps({
    "note": "GENERATED by plugins/8b8/read-params.py from generate.py in the "
            "8bit8asterd repository. Do not edit; run ./sync.sh.",
    "layoutVersion": module.layout_version(),
    "params": params,
}, ensure_ascii=False, indent=2))
