// tests/host/ground.test.js
//
// Ground through the real host path: the profile dereferences, the module
// instantiates in a worklet, and a planned bass line comes out once the
// transport rolls. Transport and conductor CCs are posted as the messages a
// host sends, and the outgoing events are read back the same way, so this
// exercises the contract's generator path rather than the Rust in isolation.
import { describe, it, expect, beforeAll } from 'vitest'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { readFile } from 'node:fs/promises'
import { PluginLoader } from '../../src/host/PluginLoader.js'
import { shapeValidatorFromFile } from '../../src/validate/files.js'
import { parseText } from '../../src/rdf/parse.js'
import { detectCapabilities } from '../../src/host/Capabilities.js'
import { Engine } from '../../src/engine/Engine.js'
import { OfflineContext, OfflineWorkletNode, directoryFetch } from '../../src/testing/OfflineHost.js'

const root = resolve(import.meta.dirname, '../..')
const pluginDir = resolve(root, 'plugins/ground')
const CANONICAL = 'https://strandz.it/jigdaw/plugins/ground/'

const SAMPLE_RATE = 48000
const TEMPO = 240
const BEATS_PER_FRAME = TEMPO / (60 * SAMPLE_RATE)

function makeLoader (validator) {
  return new PluginLoader({
    fetch: directoryFetch({ [CANONICAL]: pluginDir }),
    parse: parseText,
    validator,
    capabilities: detectCapabilities({}),
    processorUrl: () => pathToFileURL(resolve(pluginDir, 'ground-processor.js')).href
  })
}

async function makeEntry (validator) {
  const context = new OfflineContext({ sampleRate: SAMPLE_RATE })
  const engine = new Engine({ context, loader: makeLoader(validator), AudioWorkletNode: OfflineWorkletNode })
  const entry = await engine.addPlugin(CANONICAL)
  return { engine, entry, node: entry.node }
}

// Message delivery hops through the ports, so let the queue drain on a real
// tick rather than a microtask checkpoint.
const settle = () => new Promise(resolve => setTimeout(resolve, 0))

function postTransport (node) {
  node.port.postMessage({
    type: 'transport',
    playing: true,
    frame: node.frame,
    beat: node.frame * BEATS_PER_FRAME,
    beatsPerFrame: BEATS_PER_FRAME,
    tempo: TEMPO,
    timeSignature: { beatsPerBar: 4, beatUnit: 4 }
  })
}

async function drive (node, blocks, every = 1) {
  for (let b = 0; b < blocks; b++) {
    if (b % every === 0) {
      postTransport(node)
      await settle()
    }
    node.render()
  }
  await settle()
  return node.processor.port.posted
    .filter(m => m.type === 'events')
    .flatMap(m => m.events)
}

const onsets = events => events.filter(e => (e.bytes[0] & 0xf0) === 0x90 && e.bytes[2] > 0)
const signature = events => events.map(e => `${e.frame}:${[...e.bytes].join(',')}`)

describe('ground, a long-form bass generator', () => {
  let validator
  beforeAll(async () => { validator = await shapeValidatorFromFile(resolve(root, 'vocabs/shapes.ttl')) })

  it('dereferences the IRI to a generator profile with every control', async () => {
    const { profile } = await makeLoader(validator).loadProfile(CANONICAL)
    expect(profile.label).toBe('Ground')
    expect(profile.ports).toHaveLength(56)
    expect(profile.requires).toContain('http://purl.org/stuff/jigdaw/MidiEvents')
    expect(profile.requires).toContain('http://purl.org/stuff/jigdaw/MidiOut')
    expect(profile.requires).toContain('http://purl.org/stuff/transmissions/HostTransport')
    expect(profile.accepts.some(s => s.endsWith('ControlMidi'))).toBe(true)
    expect(profile.produces.some(s => s.endsWith('BassMidi'))).toBe(true)
  })

  it('declares the same parameters in the profile, the processor and the module order', async () => {
    // Three lists name the controls: profile.json ports, the processor's
    // PARAM_INDEX and parameterDescriptors, and the module's jig:paramIndex.
    // The 32 phrase roles are generated by a loop in the processor, so the
    // order check reads PARAM_INDEX while the range check reads the dials.
    const template = JSON.parse(await readFile(resolve(pluginDir, 'profile.json'), 'utf8'))
    const source = await readFile(resolve(pluginDir, 'ground-processor.js'), 'utf8')
    const indexBlock = source.slice(source.indexOf('PARAM_INDEX = Object.freeze('), source.indexOf('})', source.indexOf('PARAM_INDEX')))
    const indexed = [...indexBlock.matchAll(/(\w+):\s*(\d+)/g)].map(m => ({ symbol: m[1], index: Number(m[2]) }))
    expect(indexed.map(e => e.symbol)).toEqual(template.ports.map(p => p.symbol))
    expect(indexed.map(e => e.index)).toEqual(template.ports.map(p => p.paramIndex))
    const dials = [...source.matchAll(/dial\('([^']+)',\s*([^,]+),\s*([^,]+),\s*([^)]+)\)/g)]
    for (const [symbol, def, min, max] of dials.map(m => [m[1], Number(m[2]), Number(m[3]), Number(m[4])])) {
      const port = template.ports.find(p => p.symbol === symbol)
      expect(port, symbol).toBeDefined()
      expect(def, symbol).toBe(port.default)
      expect(min, symbol).toBe(port.minimum)
      expect(max, symbol).toBe(port.maximum)
    }
    expect(source).toMatch(/for \(let role = 1; role <= 32; role\+\+\) descriptors\.push\(dial\(`phrase_role_\$\{role\}`, 0, 0, 7\)\)/)
  })

  it('runs the init/ready handshake and reports ready', async () => {
    const { entry } = await makeEntry(validator)
    expect(entry.ready.latencyFrames).toBe(0)
    expect(entry.node).toBeInstanceOf(OfflineWorkletNode)
  })

  it('is silent until the transport rolls', async () => {
    const { node } = await makeEntry(validator)
    for (let b = 0; b < 8; b++) node.render()
    await settle()
    expect(node.processor.port.posted.filter(m => m.type === 'events')).toEqual([])
  })

  it('plays a bass line on channel 1 once the transport rolls', async () => {
    const { node } = await makeEntry(validator)
    // Sixteen beats of long-form bass: a whole phrase of onsets, or the
    // scheduler never fired. Ground is sparse by design, about two onsets
    // a bar, so this drive is long and the threshold modest.
    const events = await drive(node, 1500)
    const hits = onsets(events)
    expect(hits.length).toBeGreaterThan(5)
    for (const e of hits) {
      expect(e.bytes[0]).toBe(0x90)
      // The register lane folds everything near the root: color off would
      // pin it tighter, but even at default color the lane holds.
      expect(e.bytes[1]).toBeGreaterThanOrEqual(24)
      expect(e.bytes[1]).toBeLessThanOrEqual(60)
      expect(e.bytes[2]).toBeGreaterThanOrEqual(1)
      expect(e.bytes[2]).toBeLessThanOrEqual(127)
    }
    const frames = events.map(e => e.frame)
    expect([...frames].sort((a, b) => a - b)).toEqual(frames)
  })

  it('renders silence on its audio outputs and finite samples throughout', async () => {
    const { node } = await makeEntry(validator)
    await drive(node, 40)
    const out = node.render()
    for (const channel of out) {
      expect(channel.every(v => v === 0)).toBe(true)
      expect(channel.every(Number.isFinite)).toBe(true)
    }
  })

  it('plays the same form for the same seed, twice', async () => {
    const first = await drive((await makeEntry(validator)).node, 1000)
    const second = await drive((await makeEntry(validator)).node, 1000)
    expect(signature(second)).toEqual(signature(first))
    expect(onsets(first).length).toBeGreaterThan(3)
  })

  it('plans a fresh form on the New Form trigger', async () => {
    const plain = await makeEntry(validator)
    const before = signature(await drive(plain.node, 1000))

    // The trigger fires on the rising edge, so the press lands before the
    // first block and the whole run below plays the regenerated form.
    const pressed = await makeEntry(validator)
    pressed.engine.setParameter(pressed.entry.id, 'new_form', 1)
    const after = signature(await drive(pressed.node, 1000))

    expect(before.length).toBeGreaterThan(0)
    expect(after.length).toBeGreaterThan(0)
    expect(after).not.toEqual(before)
  })

  it('thins out when Conductor CC 21 closes the density', async () => {
    // Density differences only show over several bars: at shorter drives
    // even full density yields barely an onset, leaving no margin for the
    // comparison. Bar-start onsets sound either way, so this compares
    // counts, not silence.
    const open = await makeEntry(validator)
    open.engine.setParameter(open.entry.id, 'conductor_ch', 3)
    const wide = onsets(await drive(open.node, 1200)).length

    const steered = await makeEntry(validator)
    steered.engine.setParameter(steered.entry.id, 'conductor_ch', 3)
    // CC 21 on the conductor channel, the third MIDI channel: density to 0.
    steered.node.port.postMessage({
      type: 'events',
      events: [{ frame: steered.node.frame, bytes: Uint8Array.from([0xb2, 21, 0]) }]
    })
    await settle()
    const narrow = onsets(await drive(steered.node, 1200)).length

    expect(wide).toBeGreaterThan(narrow)
  })

  it('spreads notes across blocks when transport updates are sparse', async () => {
    // The flywheel test, as in drumgen, bassgen and melgen: Jiggy reports
    // the beat on a slow loop, and the line must sound the same as with
    // per-block updates rather than quantising to the update grid.
    const dense = await drive((await makeEntry(validator)).node, 1200, 1)
    const flown = await drive((await makeEntry(validator)).node, 1200, 150)
    expect(onsets(dense).length).toBeGreaterThan(3)
    expect(signature(flown)).toEqual(signature(dense))
  })
})
