// src/jsfx/ProcessorTemplate.js
//
// Renders a converted JSFX plugin's own AudioWorklet processor source.
//
// Not a file copied verbatim between plugins, unlike plugins/_jsfx-runtime's
// wasm module: contract section 3.1 constructs the node from
// jig:registeredName, and every plugin registers under its own name, so two
// JSFX plugins loaded into the same page cannot share one literal
// registerProcessor() call. parameterDescriptors is a static method too, and
// has to answer with THIS script's sliders, not another one's. So
// bin/jsfx-import.js renders this template once per converted plugin, the
// same reason plugins/cascade and plugins/dynamix each hand-write their own
// PARAM_INDEX and parameterDescriptors rather than sharing a file, just
// generated instead of hand-written because the sliders come from the JSFX
// header rather than from a person choosing them.
//
// The pattern below (fetch bytes on the message thread, compile and
// instantiate synchronously inside the worklet, never call fetch from
// AudioWorkletGlobalScope) is exactly plugins/cascade/cascade-processor.js's;
// the one addition is writing the compiled script into the module's memory
// from the `assets.script` bytes docs/messaging.md section 1.2 describes,
// before running it.

function jsStringLiteral (value) {
  return JSON.stringify(value)
}

/**
 * @param path this file's own path relative to the repository root, for the
 *   opening comment every tracked source file carries
 * @param registeredName the jig:registeredName this plugin's profile declares
 * @param ports [{ symbol, name, default, minimum, maximum }], slider1 first
 */
export function renderProcessor ({ path, registeredName, ports }) {
  const paramIndexEntries = ports.map((p, i) => `  ${jsStringLiteral(p.symbol)}: ${i}`).join(',\n')
  const descriptorEntries = ports.map(p =>
    `    { name: ${jsStringLiteral(p.symbol)}, defaultValue: ${p.default}, minValue: ${p.minimum}, maxValue: ${p.maximum}, automationRate: 'k-rate' }`
  ).join(',\n')

  return `// ${path}
//
// Generated by bin/jsfx-import.js from src/jsfx/ProcessorTemplate.js. Do not
// edit: rerun the importer against the source .jsfx file instead.
const PARAM_INDEX = Object.freeze({
${paramIndexEntries}
})

class JsfxProcessor extends AudioWorkletProcessor {
  static get parameterDescriptors () {
    return [
${descriptorEntries}
    ]
  }

  constructor (options) {
    super(options)
    this.ready = false
    this.exports = null
    this.inputViews = []
    this.outputViews = []
    this.lastValues = new Float32Array(Object.keys(PARAM_INDEX).length).fill(NaN)
    this.port.onmessage = event => this.handle(event.data)
  }

  handle (message) {
    if (message?.type !== 'init') return
    try {
      this.instantiate(message.module, message.assets ?? {}, message.sampleRate ?? sampleRate)
      this.ready = true
      this.port.postMessage({ type: 'ready', latencyFrames: 0, tailFrames: null })
    } catch (error) {
      this.port.postMessage({
        type: 'error', phase: 'instantiate', fatal: true, message: String(error?.message ?? error)
      })
    }
  }

  instantiate (moduleBytes, assets, rate) {
    if (!moduleBytes) throw new Error('init carried no WebAssembly bytes')
    const compiled = new WebAssembly.Module(moduleBytes)
    const instance = new WebAssembly.Instance(compiled, {})
    const exports = instance.exports

    for (const name of [
      'jig_init', 'jig_process', 'jig_input_ptr', 'jig_output_ptr', 'jig_set_param',
      'jig_script_ptr', 'jig_script_max_len', 'jig_load_script', 'jig_max_frames', 'memory'
    ]) {
      if (!(name in exports)) throw new Error(\`the module does not export \${name}\`)
    }

    exports.jig_init(rate)

    const scriptBytes = assets.script
    if (!scriptBytes) throw new Error('init carried no compiled script asset')
    if (scriptBytes.byteLength > exports.jig_script_max_len()) {
      throw new Error('compiled script is larger than the runtime\\'s script buffer')
    }
    new Uint8Array(exports.memory.buffer, exports.jig_script_ptr(), scriptBytes.byteLength)
      .set(new Uint8Array(scriptBytes))
    exports.jig_load_script(scriptBytes.byteLength)

    const maxFrames = exports.jig_max_frames()
    const buffer = exports.memory.buffer
    for (let channel = 0; channel < 2; channel++) {
      this.inputViews.push(new Float32Array(buffer, exports.jig_input_ptr(channel), maxFrames))
      this.outputViews.push(new Float32Array(buffer, exports.jig_output_ptr(channel), maxFrames))
    }

    this.exports = exports
    this.maxFrames = maxFrames
  }

  process (inputs, outputs, parameters) {
    const output = outputs[0]
    if (!output || output.length === 0) return true

    if (!this.ready) {
      for (const channel of output) channel.fill(0)
      return true
    }

    const frames = Math.min(output[0].length, this.maxFrames)
    const input = inputs[0]

    for (let channel = 0; channel < 2; channel++) {
      const source = input && input.length > 0 ? input[Math.min(channel, input.length - 1)] : null
      const view = this.inputViews[channel]
      if (source) view.set(source.subarray(0, frames))
      else view.fill(0, 0, frames)
    }

    for (const [name, index] of Object.entries(PARAM_INDEX)) {
      const values = parameters[name]
      if (!values) continue
      const value = values.length === 1 ? values[0] : values[values.length - 1]
      if (value !== this.lastValues[index]) {
        this.exports.jig_set_param(index, value)
        this.lastValues[index] = value
      }
    }

    this.exports.jig_process(frames)

    for (let channel = 0; channel < output.length; channel++) {
      const view = this.outputViews[Math.min(channel, 1)]
      output[channel].set(view.subarray(0, frames))
      if (frames < output[channel].length) output[channel].fill(0, frames)
    }

    return true
  }
}

registerProcessor(${jsStringLiteral(registeredName)}, JsfxProcessor)
`
}
