// src/rdf/ProvenanceDocument.js
//
// The provenance record a bundle carries, as Turtle and back.
//
// docs/plugin-bundles.md section 5. It says what a recipient cannot work out
// for themselves: a bundle arrives by hand rather than from the origin that
// minted the IRI inside it, so where it has been is the one fact that is not
// already in the profile.
//
// Three nodes, all with IRIs and none of them blank, because the signed form is
// a canonicalisation and a blank node has no stable name. They are fragments of
// the provenance document's own IRI, written absolutely so that the same bytes
// mean the same thing whether the record is a file next to the profile or
// appended to a flattened one. The default document IRI sits beside the profile,
// which is right for an author bundling their own plugin and wrong for anybody
// else, so a third party states their own with `documentIri`.
//
// Deterministic apart from the time, which is the one thing the record exists to
// carry. See the note on reproducibility in bin/bundle.js.
import { vocabulary as v, JIG, TRN, PROV, SEC, DCTERMS, XSD } from './Vocabulary.js'

const { jig, prov, sec, dcterms } = v

const PREFIXES = [
  ['jig', JIG],
  ['trn', TRN],
  ['prov', PROV],
  ['sec', SEC],
  ['dcterms', DCTERMS],
  ['rdfs', 'http://www.w3.org/2000/01/rdf-schema#'],
  ['xsd', XSD]
]

function term (iri) {
  for (const [prefix, namespace] of PREFIXES) {
    if (iri.startsWith(namespace)) return `${prefix}:${iri.slice(namespace.length)}`
  }
  return `<${iri}>`
}

const string = value => JSON.stringify(String(value))
const dateTime = value => `${string(new Date(value).toISOString())}^^xsd:dateTime`

/** Where the record's own nodes are named, when nobody says otherwise. */
export const provenanceIriFor = profileIri => `${profileIri}provenance.ttl`

/**
 * The record as Turtle.
 *
 * A proof with no `proofValue` is emitted without sec:proofValue, which is how
 * signing works: the graph is written once to be canonicalised and signed, then
 * once more with the signature in it. Everything else about the proof, the key
 * and the time, is in the graph the first time and so is covered by it.
 */
export function writeProvenance (record) {
  const {
    profileIri,
    documentIri = provenanceIriFor(profileIri),
    form,
    canonicalDigest,
    endedAtTime,
    tool,
    toolName = null,
    attributedTo = null,
    atLocation = null,
    proof = null
  } = record

  if (!profileIri) throw new Error('a provenance record must name the profile it is about')
  if (!form) throw new Error('a provenance record must say which form the bundle is')
  if (!canonicalDigest) throw new Error('a provenance record must carry the canonical digest')
  if (!tool) throw new Error('a provenance record must name the tool that made the bundle')

  const bundle = `${documentIri}#bundle`
  const bundling = `${documentIri}#bundling`
  const proofIri = `${documentIri}#proof`

  const lines = []
  lines.push(`# ${documentIri}`)
  lines.push('#')
  lines.push('# Who made this copy of the plugin, when, and with what. Generated by')
  lines.push('# bin/bundle.js; see docs/plugin-bundles.md section 5.')
  lines.push('')
  for (const [prefix, namespace] of PREFIXES) lines.push(`@prefix ${prefix}: <${namespace}> .`)
  lines.push('')

  lines.push(`<${bundle}>`)
  lines.push(`    a ${term(jig.Bundle)} ;`)
  lines.push(`    ${term(prov.wasDerivedFrom)} <${profileIri}> ;`)
  lines.push(`    ${term(jig.bundleForm)} ${term(form)} ;`)
  lines.push(`    ${term(jig.canonicalDigest)} ${string(canonicalDigest)} ;`)
  lines.push(`    ${term(prov.wasGeneratedBy)} <${bundling}> .`)
  lines.push('')

  lines.push(`<${bundling}>`)
  lines.push(`    a ${term(jig.Bundling)} ;`)
  lines.push(`    ${term(prov.used)} <${profileIri}> ;`)
  lines.push(`    ${term(prov.endedAtTime)} ${dateTime(endedAtTime)} ;`)
  if (atLocation) lines.push(`    ${term(prov.atLocation)} <${atLocation}> ;`)
  if (attributedTo) lines.push(`    ${term(prov.wasAttributedTo)} <${attributedTo}> ;`)
  if (toolName) lines.push(`    rdfs:label ${string(toolName)} ;`)
  lines.push(`    ${term(prov.wasAssociatedWith)} <${tool}> .`)

  if (proof) {
    lines.push('')
    lines.push(`<${profileIri}> ${term(sec.proof)} <${proofIri}> .`)
    lines.push('')
    lines.push(`<${proofIri}>`)
    lines.push(`    a ${term(sec.DataIntegrityProof)} ;`)
    lines.push(`    ${term(sec.cryptosuite)} ${string(proof.cryptosuite)} ;`)
    lines.push(`    ${term(sec.proofPurpose)} ${term(sec.assertionMethod)} ;`)
    lines.push(`    ${term(sec.verificationMethod)} <${proof.verificationMethod}> ;`)
    if (proof.proofValue) lines.push(`    ${term(sec.proofValue)} ${string(proof.proofValue)} ;`)
    lines.push(`    ${term(dcterms.created)} ${dateTime(proof.created)} .`)
    lines.push('')
    lines.push(`<${proof.verificationMethod}>`)
    lines.push(`    a ${term(sec.Multikey)} ;`)
    lines.push(`    ${term(sec.publicKeyMultibase)} ${string(proof.publicKeyMultibase)} .`)
  }

  lines.push('')
  return lines.join('\n')
}

/** The IRIs writeProvenance will mint, so a caller can name the proof node. */
export const provenanceNodes = documentIri => Object.freeze({
  bundle: `${documentIri}#bundle`,
  bundling: `${documentIri}#bundling`,
  proof: `${documentIri}#proof`
})

// ── Reading ────────────────────────────────────────────────────────────────

const one = (dataset, subject, predicate) => {
  for (const quad of dataset) {
    if (quad.subject.value === subject && quad.predicate.value === predicate) return quad.object.value
  }
  return null
}

/**
 * The record as data, or null when a bundle carries none.
 *
 * Deliberately does not verify anything. A caller that wants to know whether
 * this is true asks src/host/Signature.js, and one that renders the answer says
 * which of the two it is asking.
 */
export function readProvenance (dataset) {
  const bundle = [...dataset].find(q =>
    q.predicate.value === v.rdf.type && q.object.value === jig.Bundle)?.subject.value
  if (!bundle) return null

  const bundling = one(dataset, bundle, prov.wasGeneratedBy)
  return {
    bundle,
    of: one(dataset, bundle, prov.wasDerivedFrom),
    form: one(dataset, bundle, jig.bundleForm),
    canonicalDigest: one(dataset, bundle, jig.canonicalDigest),
    bundling,
    endedAtTime: bundling ? one(dataset, bundling, prov.endedAtTime) : null,
    attributedTo: bundling ? one(dataset, bundling, prov.wasAttributedTo) : null,
    atLocation: bundling ? one(dataset, bundling, prov.atLocation) : null,
    tool: bundling ? one(dataset, bundling, prov.wasAssociatedWith) : null
  }
}
