#!/usr/bin/env bash
# plugins/mop/build.sh
#
# Build the wasm, then generate profile.ttl with the digests of the files that
# were actually produced. The profile is generated rather than hand-edited
# because a digest written by hand is a digest that goes stale on the next
# build, silently, and the failure is a refused plugin.
#
# No Emscripten. A JigDAW module must instantiate with no imports
# (docs/module-abi.md), and an emcc build brings a libc and its imports with
# it, so this is clang targeting wasm32 with -nostdlib and wasm-ld doing the
# link. shim/ supplies the few libc functions that leaves missing.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../.." && pwd)"
cd "$here"

build="$here/build"
mkdir -p "$build"

CXX="${CXX:-clang++}"
CC="${CC:-clang}"
command -v "$CXX" >/dev/null || { echo "$CXX not found" >&2; exit 1; }
command -v "$CC" >/dev/null || { echo "$CC not found" >&2; exit 1; }
CXX_PROBE="$CXX"

# ---- the linker -------------------------------------------------------------
if command -v wasm-ld >/dev/null; then
  : # already on PATH
else
  rustlld="$(find "${RUSTUP_HOME:-$HOME/.rustup}/toolchains" -name rust-lld -type f -print -quit 2>/dev/null || true)"
  [ -n "$rustlld" ] || {
    echo "no wasm-ld and no rust-lld: install lld (see HUMANS.md) or a rust toolchain" >&2
    exit 1
  }
  ln -sf "$rustlld" "$build/wasm-ld"
  ln -sf "$rustlld" "$build/wasm-ld-$("$CXX_PROBE" -dumpversion | cut -d. -f1)"
  PATH="$build:$PATH"
fi

# ---- the bank, embedded -----------------------------------------------------
# The module is self-contained: a worklet cannot fetch, so mop.bnk travels in
# the wasm rather than beside it. The .bnk stays in the directory as the
# provenance of these bytes.
python3 - "$here/mop.bnk" "$build/bank.h" <<'EOF'
import sys
src, dst = sys.argv[1], sys.argv[2]
data = open(src, 'rb').read()
with open(dst, 'w') as f:
    f.write('// build/bank.h\n//\n')
    f.write('// GENERATED by plugins/mop/build.sh from mop.bnk. Do not edit.\n')
    f.write('#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n')
    f.write(f'static const size_t BANK_SIZE = {len(data)};\n')
    f.write('static const uint8_t BANK_DATA[] = {\n')
    for i in range(0, len(data), 12):
        f.write('  ' + ', '.join(f'{b:#04x}' for b in data[i:i+12]) + ',\n')
    f.write('};\n')
print(f'bank: {len(data)} bytes', file=sys.stderr)
EOF

# ---- compile ----------------------------------------------------------------
cflags=(
  --target=wasm32 -O2 -nostdlib
  -fno-exceptions -fno-rtti -fno-threadsafe-statics
  -I"$here" -I"$here/shim" -I"$build"
)
"$CC" "${cflags[@]}" -std=c11 -c opal/opal.c -o "$build/opal.o"
"$CXX" "${cflags[@]}" -std=c++17 -c mop.cpp -o "$build/mop.o"
"$CXX" "${cflags[@]}" -std=c++17 -c shim/nostdlib.cpp -o "$build/nostdlib.o"

# ---- link -------------------------------------------------------------------
# --no-entry because there is no main. Every export is named, rather than
# --export-all: an export is part of the ABI and a list is a thing a reader
# can check against docs/module-abi.md.
#
# --allow-undefined is deliberately NOT passed. A module that resolves a
# missing symbol to an import is a module that fails to instantiate in the
# host with no imports to give it, and it fails at load rather than at build,
# which is the wrong end.
"$CXX" "${cflags[@]}" -o "$build/mop.wasm" \
  "$build/mop.o" "$build/opal.o" "$build/nostdlib.o" \
  -Wl,--no-entry \
  -Wl,--export=jig_init \
  -Wl,--export=jig_max_frames \
  -Wl,--export=jig_output_ptr \
  -Wl,--export=jig_process \
  -Wl,--export=jig_set_param \
  -Wl,--export=jig_midi_in_ptr \
  -Wl,--export=jig_midi_in_capacity \
  -Wl,--export=jig_midi_in \
  -Wl,--export=jig_latency_frames \
  -Wl,--export=jig_active_voices \
  -Wl,--export=jig_channel_program \
  -Wl,--export-memory

cp "$build/mop.wasm" "$here/mop.wasm"

node "$root/bin/write-profile.js" "$here"
echo "built $(wc -c < mop.wasm) bytes of wasm, profile.ttl regenerated"
