// web/precache.js
// Generated by bin/build-precache.js. Do not edit: npm run build:precache.
self.APP_PRECACHE = {
  "version": "7b06c22c91d2",
  "files": [
    {
      "path": "./",
      "hash": "88d1d71e7d62ed0c"
    },
    {
      "path": "app.bundle.js",
      "hash": "7fb41c9c5b767ec9"
    },
    {
      "path": "simple.html",
      "hash": "3f9be8098d9eea4e"
    },
    {
      "path": "simple.bundle.js",
      "hash": "fe910d29972128e0"
    },
    {
      "path": "panel.css",
      "hash": "fefbd4256d73e85e"
    },
    {
      "path": "host.json",
      "hash": "ff5d33d3b6ac5059"
    },
    {
      "path": "manifest.webmanifest",
      "hash": "3892659196b0546f"
    },
    {
      "path": "vocabs/shapes.ttl",
      "hash": "75719ceac05ec48b"
    },
    {
      "path": "icons/apple-touch-icon.png",
      "hash": "c4a6e0d7a1ce1047"
    },
    {
      "path": "icons/icon-192.png",
      "hash": "dac1b86d09abac8c"
    },
    {
      "path": "icons/icon-512.png",
      "hash": "9fccb29f8d3f2a6c"
    },
    {
      "path": "icons/icon-maskable-512.png",
      "hash": "974668f5c639a319"
    },
    {
      "path": "presets/acid.ttl",
      "hash": "c959faced1572cc3"
    },
    {
      "path": "presets/amp-into-room.ttl",
      "hash": "7e4c54e23b7aa8a4"
    },
    {
      "path": "presets/chiptune.ttl",
      "hash": "edfed680a29c92c8"
    },
    {
      "path": "presets/fender-into-the-ropery.ttl",
      "hash": "aef35d06e7e5a858"
    },
    {
      "path": "presets/fugue.ttl",
      "hash": "e838bdd238dedee8"
    },
    {
      "path": "presets/index.json",
      "hash": "4a65189312c1d7d6"
    },
    {
      "path": "presets/pulse-tremolo-plate.ttl",
      "hash": "205f4d44a94d74c7"
    }
  ]
}
