// web/precache.js
// Generated by bin/build-precache.js. Do not edit: npm run build:precache.
self.APP_PRECACHE = {
  "version": "82a24fe0ec65",
  "files": [
    {
      "path": "./",
      "hash": "40480011973fcc0c"
    },
    {
      "path": "app.bundle.js",
      "hash": "6740c1d56c893b01"
    },
    {
      "path": "simple.html",
      "hash": "91d03dc1e56eb695"
    },
    {
      "path": "view.js",
      "hash": "452ed0f4d473a7f7"
    },
    {
      "path": "simple.bundle.js",
      "hash": "6228df03bc0b8f2b"
    },
    {
      "path": "panel.css",
      "hash": "6985499d3e3cc3dd"
    },
    {
      "path": "host.json",
      "hash": "fbdb959e7f9e1497"
    },
    {
      "path": "manifest.webmanifest",
      "hash": "640724d84a8b3260"
    },
    {
      "path": "vocabs/shapes.ttl",
      "hash": "8467f2f80ef0e9aa"
    },
    {
      "path": "icons/apple-touch-icon.png",
      "hash": "c4a6e0d7a1ce1047"
    },
    {
      "path": "icons/icon-192.png",
      "hash": "dac1b86d09abac8c"
    },
    {
      "path": "icons/icon-512.png",
      "hash": "9fccb29f8d3f2a6c"
    },
    {
      "path": "icons/icon-maskable-512.png",
      "hash": "974668f5c639a319"
    },
    {
      "path": "presets/acid.ttl",
      "hash": "c959faced1572cc3"
    },
    {
      "path": "presets/amp-into-room.ttl",
      "hash": "429e8c87208cb60d"
    },
    {
      "path": "presets/chiptune.ttl",
      "hash": "edfed680a29c92c8"
    },
    {
      "path": "presets/fender-into-the-ropery.ttl",
      "hash": "5149067de0e0f05f"
    },
    {
      "path": "presets/fugue.ttl",
      "hash": "e838bdd238dedee8"
    },
    {
      "path": "presets/generative-fx.ttl",
      "hash": "4bff0b68eba7c8a2"
    },
    {
      "path": "presets/index.json",
      "hash": "9b153490356fd714"
    },
    {
      "path": "presets/keyframe.ttl",
      "hash": "6ff448694f751a44"
    }
  ]
}
