// web/precache.js
// Generated by bin/build-precache.js. Do not edit: npm run build:precache.
self.APP_PRECACHE = {
  "version": "0336262d9cd2",
  "files": [
    {
      "path": "./",
      "hash": "bd4489e4d6d90798"
    },
    {
      "path": "app.bundle.js",
      "hash": "3c03f51a47fb3cf6"
    },
    {
      "path": "simple.html",
      "hash": "3184dba4260d460e"
    },
    {
      "path": "simple.bundle.js",
      "hash": "6981ad7c43d538f8"
    },
    {
      "path": "panel.css",
      "hash": "fefbd4256d73e85e"
    },
    {
      "path": "host.json",
      "hash": "ff5d33d3b6ac5059"
    },
    {
      "path": "manifest.webmanifest",
      "hash": "640724d84a8b3260"
    },
    {
      "path": "vocabs/shapes.ttl",
      "hash": "4859b52e0693b256"
    },
    {
      "path": "icons/apple-touch-icon.png",
      "hash": "c4a6e0d7a1ce1047"
    },
    {
      "path": "icons/icon-192.png",
      "hash": "dac1b86d09abac8c"
    },
    {
      "path": "icons/icon-512.png",
      "hash": "9fccb29f8d3f2a6c"
    },
    {
      "path": "icons/icon-maskable-512.png",
      "hash": "974668f5c639a319"
    },
    {
      "path": "presets/acid.ttl",
      "hash": "c959faced1572cc3"
    },
    {
      "path": "presets/amp-into-room.ttl",
      "hash": "429e8c87208cb60d"
    },
    {
      "path": "presets/chiptune.ttl",
      "hash": "edfed680a29c92c8"
    },
    {
      "path": "presets/fender-into-the-ropery.ttl",
      "hash": "5149067de0e0f05f"
    },
    {
      "path": "presets/fugue.ttl",
      "hash": "e838bdd238dedee8"
    },
    {
      "path": "presets/generative-fx.ttl",
      "hash": "4bff0b68eba7c8a2"
    },
    {
      "path": "presets/index.json",
      "hash": "269760d972915ab0"
    }
  ]
}
